name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir ./release
          zip -r ./release/pagepouch-source.zip ./* -x ./release/*
          npm i
          npm run build:v2
          cd ./dist
          zip -r ../release/pagepouch-v2.zip ./*
          rm -r ./*
          npm run build:v3
          zip -r ../release/pagepouch-v3.zip ./*
          
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./release/*
