name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir ./release
          zip -r ./release/pagepouch-source.zip ./* -x ./release/*
          
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./release/*
